import React from 'react'
import Link from 'next/link'
import style from "./style.module.css"
export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
  metadata: "It is blog website",
};

const about = () => {
  // when error occur error file load automatically
  // throw new Error("New Error occur")
  return (
    <div className={style.main}>
        <Link href={"/"}>Home</Link>
    </div>
  )
}

export default about; 
