import './globals.css'
import { Metadata } from 'next';
import { Inter } from 'next/font/google'; //we are using this for defining google font for our project
const inter= Inter({subsets:['latin']})
// metadata of next describing all data field in that set of document
export const metadata :Metadata= {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
              {children}
      </body>
    </html>
  );
}
